#!/bin/bash
SUBCOMMAND="$1"; shift
if [ -z "$SUBCOMMAND" ]; then
  SUBCOMMAND=help
fi

BINDIR="$INSTALLDIR"/bin
LIBDIR="$INSTALLDIR"/lib
. "$INSTALLDIR"/config/tdm.sh

if [ -r "$INSTALLDIR"/lib/commands/"$SUBCOMMAND" ]; then
  set -e
  . "$INSTALLDIR"/lib/commands/"$SUBCOMMAND"
  echo "Subcommand $SUBCOMMAND did not exit properly."
  exit 99
fi
echo "$SUBCOMMAND" is not a valid subcommand. Try "tdm help" for a list.
exit 1
